# Generated by Django 4.2.29 on 2026-03-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='LNGSHOT')),
                ('debut_date', models.DateField(verbose_name='2026年1月13日')),
                ('company', models.CharField(max_length=100, verbose_name='MOREVISION')),
                ('description', models.TextField(verbose_name='团体简介')),
                ('group_photo', models.ImageField(upload_to='groups/', verbose_name='团体大合照')),
            ],
            options={
                'verbose_name': '偶像团体',
                'verbose_name_plural': '偶像团体',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='本名')),
                ('stage_name', models.CharField(max_length=100, verbose_name='艺名')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('position', models.CharField(help_text='例如：主唱 / 领舞', max_length=100, verbose_name='队内担当')),
                ('mbti', models.CharField(blank=True, max_length=4, verbose_name='MBTI')),
                ('bio', models.TextField(verbose_name='个人简介')),
                ('photo', models.ImageField(upload_to='members/', verbose_name='个人照片')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='wiki.idolgroup', verbose_name='所属团体')),
            ],
            options={
                'verbose_name': '成员资料',
                'verbose_name_plural': '成员资料',
            },
        ),
    ]
