# Generated by Django 4.2.29 on 2026-03-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='video_url',
            field=models.URLField(blank=True, help_text='请输入 Bilibili 或 YouTube 的分享嵌入链接', verbose_name='直拍/MV链接'),
        ),
        migrations.AlterField(
            model_name='idolgroup',
            name='debut_date',
            field=models.DateField(verbose_name='出道日期'),
        ),
        migrations.AlterField(
            model_name='idolgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='团队名称'),
        ),
    ]
