# Generated by Django 4.2.29 on 2026-03-25 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_member_video_url_alter_idolgroup_debut_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='专辑名称')),
                ('cover', models.ImageField(upload_to='albums/', verbose_name='专辑封面')),
                ('release_date', models.DateField(verbose_name='发行日期')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='wiki.idolgroup', verbose_name='所属团体')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='歌曲名称')),
                ('order', models.IntegerField(default=1, verbose_name='曲序')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='wiki.album', verbose_name='所属专辑')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['order'],
            },
        ),
    ]
