# Generated by Django 4.2.29 on 2026-03-25 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_album_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RemoveField(
            model_name='member',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='wiki.idolgroup'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(upload_to='members/', verbose_name='成员封面主图'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(max_length=100, verbose_name='队内担当'),
        ),
        migrations.CreateModel(
            name='MemberSelfIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='member_self_intro/', verbose_name='自述图/简历图')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='图片标题')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_intros', to='wiki.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='member_gallery/', verbose_name='相册美照')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wiki.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberFancam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='直拍舞台名')),
                ('video_url', models.CharField(max_length=500, verbose_name='嵌入链接(src内容)')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fancams', to='wiki.member')),
            ],
        ),
    ]
