# Generated by Django 4.2.29 on 2026-03-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_member_options_remove_member_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberfancam',
            options={'verbose_name': '个人直拍', 'verbose_name_plural': '精彩直拍视频流'},
        ),
        migrations.AddField(
            model_name='memberfancam',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='fancam_covers/', verbose_name='视频封面'),
        ),
    ]
