# Generated by Django 4.2.29 on 2026-03-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_memberfancam_options_memberfancam_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membergallery',
            options={'verbose_name': '个人照片', 'verbose_name_plural': '个人相册'},
        ),
        migrations.AddField(
            model_name='membergallery',
            name='category',
            field=models.CharField(choices=[('WEVERSE', 'Weverse 动态'), ('STAGE', '舞台直击'), ('AIRPORT', '机场街拍'), ('OTHER', '其他日常')], default='OTHER', max_length=20, verbose_name='照片分类'),
        ),
        migrations.AlterField(
            model_name='membergallery',
            name='image',
            field=models.ImageField(upload_to='member_gallery/', verbose_name='相册照片'),
        ),
    ]
