# Generated by Django 4.2.29 on 2026-03-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_membergallery_options_membergallery_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='music_url',
            field=models.URLField(blank=True, verbose_name='试听链接'),
        ),
    ]
