# Generated by Django 4.2.29 on 2026-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_album_music_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='preview_audio',
            field=models.FileField(blank=True, null=True, upload_to='album_previews/', verbose_name='试听音频'),
        ),
        migrations.AddField(
            model_name='album',
            name='preview_duration',
            field=models.PositiveIntegerField(default=15, verbose_name='试听时长'),
        ),
        migrations.AddField(
            model_name='album',
            name='preview_start',
            field=models.PositiveIntegerField(default=0, verbose_name='试听开始秒数'),
        ),
        migrations.AlterField(
            model_name='album',
            name='music_url',
            field=models.URLField(blank=True, verbose_name='完整音乐链接'),
        ),
    ]
