# Generated by Django 4.2.29 on 2026-03-26 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_album_preview_audio_album_preview_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='物料标题')),
                ('category', models.CharField(choices=[('MV', 'MV'), ('SHORT', '短视频'), ('VARIETY', '综艺'), ('BEHIND', '幕后花絮'), ('LIVE', '直播'), ('SPECIAL', '特别内容'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='物料分类')),
                ('series', models.CharField(blank=True, max_length=100, verbose_name='系列名称')),
                ('cover', models.ImageField(upload_to='official_media/covers/', verbose_name='物料封面')),
                ('video_url', models.URLField(max_length=500, verbose_name='视频链接')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_media', to='wiki.idolgroup', verbose_name='所属团体')),
            ],
            options={
                'verbose_name': '官方物料',
                'verbose_name_plural': '官方物料',
                'ordering': ['category', 'series', 'sort_order', '-release_date'],
            },
        ),
    ]
