# Generated by Django 4.2.29 on 2026-03-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_officialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialmedia',
            options={'ordering': ['sort_order', '-release_date'], 'verbose_name': '官方物料', 'verbose_name_plural': '官方物料'},
        ),
        migrations.RemoveField(
            model_name='officialmedia',
            name='category',
        ),
        migrations.RemoveField(
            model_name='officialmedia',
            name='group',
        ),
        migrations.AlterField(
            model_name='officialmedia',
            name='cover',
            field=models.ImageField(upload_to='official_media/covers/', verbose_name='单集封面'),
        ),
        migrations.AlterField(
            model_name='officialmedia',
            name='title',
            field=models.CharField(max_length=200, verbose_name='单集标题'),
        ),
        migrations.CreateModel(
            name='MediaSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='系列名称')),
                ('category', models.CharField(choices=[('MV', 'MV'), ('SHORT', '短视频'), ('VARIETY', '综艺'), ('BEHIND', '幕后花絮'), ('LIVE', '直播'), ('SPECIAL', '特别内容'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='物料分类')),
                ('cover', models.ImageField(upload_to='media_series/', verbose_name='系列封面')),
                ('description', models.TextField(blank=True, verbose_name='系列简介')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_series', to='wiki.idolgroup', verbose_name='所属团体')),
            ],
            options={
                'verbose_name': '官方物料系列',
                'verbose_name_plural': '官方物料系列',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='officialmedia',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wiki.mediaseries', verbose_name='所属系列'),
        ),
    ]
