# Generated by Django 4.2.29 on 2026-03-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_alter_officialmedia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动名称')),
                ('event_type', models.CharField(choices=[('comeback', '回归'), ('music_show', '打歌'), ('fanmeeting', '见面会'), ('variety', '综艺'), ('airport', '机场'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类型')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='封面')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '成员', 'verbose_name_plural': '成员'},
        ),
        migrations.AlterModelOptions(
            name='memberselfintro',
            options={'verbose_name': '成员自述图片', 'verbose_name_plural': '成员自述图片集'},
        ),
        migrations.AlterField(
            model_name='idolgroup',
            name='company',
            field=models.CharField(max_length=100, verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='wiki.idolgroup', verbose_name='所属团体'),
        ),
        migrations.AlterField(
            model_name='memberfancam',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fancams', to='wiki.member', verbose_name='所属成员'),
        ),
        migrations.AlterField(
            model_name='membergallery',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wiki.member', verbose_name='所属成员'),
        ),
        migrations.AlterField(
            model_name='memberselfintro',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_intros', to='wiki.member', verbose_name='所属成员'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wiki.event', verbose_name='所属活动')),
                ('members', models.ManyToManyField(blank=True, related_name='album_photos', to='wiki.member', verbose_name='相关成员')),
            ],
            options={
                'verbose_name': '活动图片',
                'verbose_name_plural': '活动图片',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wiki.idolgroup', verbose_name='所属团体'),
        ),
    ]
