# Generated by Django 4.2.29 on 2026-03-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_event_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('comeback', 'wvs自拍'), ('music_show', '打歌'), ('fanmeeting', '见面会'), ('variety', '综艺'), ('airport', '机场'), ('other', 'Weverse')], default='other', max_length=20, verbose_name='活动类型'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='行程标题')),
                ('date', models.DateField(verbose_name='日期')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='场地')),
                ('schedule_type', models.CharField(choices=[('performance', '演出'), ('fanmeeting', '见面会'), ('fansign', '签售'), ('airport', '机场'), ('recording', '录制'), ('festival', '音乐节'), ('other', '其他')], default='other', max_length=20, verbose_name='行程类型')),
                ('status', models.CharField(choices=[('past', '已结束'), ('current', '进行中'), ('upcoming', '即将开始')], default='upcoming', max_length=20, verbose_name='状态')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='wiki.idolgroup', verbose_name='所属团体')),
            ],
            options={
                'verbose_name': '团体行程',
                'verbose_name_plural': '团体行程',
                'ordering': ['date', 'sort_order', 'id'],
            },
        ),
    ]
