# Generated by Django 4.2.29 on 2026-03-29 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_alter_event_event_type_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('xiaohongshu', '小红书'), ('bilibili', '哔哩哔哩'), ('weibo', '微博'), ('douyin', '抖音'), ('other', '其他')], max_length=30, verbose_name='平台')),
                ('account_name', models.CharField(max_length=100, verbose_name='账号名称')),
                ('profile_url', models.URLField(verbose_name='账号链接')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='china_social_accounts/', verbose_name='账号头像')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='china_social_accounts', to='wiki.idolgroup', verbose_name='所属团体')),
            ],
            options={
                'verbose_name': '中国平台账号',
                'verbose_name_plural': '中国平台账号',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
