# Generated by Django 4.2.29 on 2026-03-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_chinasocialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站子名称')),
                ('weibo_name', models.CharField(max_length=100, verbose_name='微博账号名')),
                ('weibo_url', models.URLField(verbose_name='微博主页链接')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='fan_stations/', verbose_name='头像')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='简介')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_stations', to='wiki.idolgroup', verbose_name='所属团体')),
            ],
            options={
                'verbose_name': '摆摊区站子',
                'verbose_name_plural': '摆摊区站子',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
