# Generated by Django 4.2.29 on 2026-03-29 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_fanstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('reaction', 'Reaction'), ('analysis', '粉丝解读'), ('meme', '梗/趣味内容'), ('moment', '名场面分析'), ('other', '其他')], default='other', max_length=30, verbose_name='分类')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='fan_reactions/', verbose_name='封面图')),
                ('source_url', models.URLField(verbose_name='原链接')),
                ('summary', models.TextField(blank=True, verbose_name='简介')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_reactions', to='wiki.idolgroup', verbose_name='所属团体')),
            ],
            options={
                'verbose_name': '烧烤一下',
                'verbose_name_plural': '烧烤一下',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
